name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # "yocto_core" package settings must have "embedded_linux_dockerfiles" added as a source repository with write permissions
  build:
    env:
      DISTRO: fsl-imx-fb
      MACHINE: imx6ulevk
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_imx:ubuntu2204'
    steps:
      - name: test node
        run: |
           echo "Checking for a usable node in /__e/node"
           for f in /__e/node*/bin/node; do
               echo "Testing: $f --version";
               $f --version || echo "$f does not work, exit status: $?"
           done
      - name: Check out code
        uses: actions/checkout@v3
      - name: test
        run: echo hello
      # - name: build linux 
      #   run: |
      #     cd imx_yocto_bsp
      #     repo init -u https://github.com/nxp-imx/imx-manifest -b imx-linux-langdale -m imx-6.1.1-1.0.0.xml
      #     repo sync
      #     ./setup-environment
          
