name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # "yocto_core" package settings must have "embedded_linux_dockerfiles" added as a source repository with write permissions
  build:
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_imx:ubuntu2204'
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: build linux 
        run: |
          cd imx_yocto_bsp
          repo init -u https://github.com/nxp-imx/imx-manifest -b imx-linux-langdale -m imx-6.1.1-1.0.0.xml
          repo sync
          ls -al
          ls -al sources/base
          ./setup-environment
          DISTRO=fsl-imx-fb MACHINE=imx6ulevk source ./imx-setup-release.sh -b build
          ./bitbake core-image-base
      
