name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # "yocto_core" package settings must have "embedded_linux_dockerfiles" added as a source repository with write permissions
  build:
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_imx:ubuntu2204'
    steps:
      - uses: actions/checkout@v3
      - name: build linux 
        run: |
          cd imx_yocto_bsp
          pwd
          ./setup-environment
          DISTRO=fsl-imx-fb MACHINE=imx6ulevk source imx-setup-release.sh -b /workspaces/imx_test/imx_yocto_bsp/build
          bitbake core-image-base
      
