name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    env:
      DISTRO: fsl-imx-fb
      MACHINE: imx6ulevk
    runs-on: [self-hosted, linux]
    container:
      image: 'ghcr.io/cracked-machine/yocto_imx:ubuntu2204'
    steps:
        # only v1 works within a self-hosted containerized actions-runner :(
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: 'true'

      - name: build linux 
        run: |
          cd imx_yocto_bsp
          repo init -u https://github.com/nxp-imx/imx-manifest -b imx-linux-langdale -m imx-6.1.1-1.0.0.xml
          repo sync
          ./setup-environment
          
